name: slomon
description: "2024_2 Capstone"
publish_to: 'none' # Prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # Cupertino Icons for iOS
  cupertino_icons: ^1.0.8

  # Additional dependencies
  flutter_chart: ^0.1.6
  http: ^1.2.2
  flutter_blue_plus: ^1.6.0
  intl: ^0.18.0

  provider: ^6.0.5

  # Local dependency
  flutter_bluetooth_serial:
    path: ./flutter_bluetooth_serial

  # ScopedModel 상태 관리 패키지
  scoped_model: ^2.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

#  integration_test: ^2.0.0

  # 통합 테스트 패키지 (중복 제거 후 단일 버전 유지)

flutter:
  fonts:
    - family: body
      fonts:
        - asset: assets/fonts/free5Medium.ttf
    - family: head
      fonts:
        - asset: assets/fonts/free7Bold.ttf

  assets:
    - assets/images/speed.png
    - assets/images/profile.png
    - assets/images/delete.png

  uses-material-design: true
